# Generated by Django 3.2.23 on 2024-01-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Goods',
        ),
    ]
