# Generated by Django 3.2.23 on 2024-01-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_db', '0002_rename_items_goods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Item',
        ),
    ]
